output "cloudfront_domain_name" {
  value       = module.frontend.cloudfront_domain_name
  description = "Domain name generated by CloudFront"
}

output "cloudfront_id" {
  value       = module.frontend.cloudfront_id
  description = "ID of the CloudFront distribution"
}

output "table_name" {
  value       = module.database.table_name
  description = "DynamoDB table name (consumed by SAM)"
}

output "files_bucket_name" {
  value       = module.files.bucket_id
  description = "S3 bucket name for user files (consumed by SAM)"
}
