output "cloudfront_domain_name" {
  value       = module.frontend.cloudfront_domain_name
  description = "Domain name generated by CloudFront"
}

output "cloudfront_id" {
  value       = module.frontend.cloudfront_id
  description = "ID of the CloudFront distribution"
}
