output "cloudfront_domain_name" {
  value       = module.frontend.cloudfront_domain_name
  description = "Domain name generated by CloudFront"
}

output "cloudfront_id" {
  value       = module.frontend.cloudfront_id
  description = "ID of the CloudFront distribution"
}

output "api_endpoint" {
  value       = aws_apigatewayv2_api.api.api_endpoint
  description = "API Gateway endpoint URL"
}

output "api_id" {
  value       = aws_apigatewayv2_api.api.id
  description = "API Gateway ID"
}

output "cognito_pool_id" {
  value       = module.auth.pool_id
  description = "Cognito User Pool ID"
}

output "cognito_client_id" {
  value       = module.auth.client_id
  description = "Cognito User Pool Client ID (for frontend)"
}

output "cognito_domain" {
  value       = module.auth.domain
  description = "Cognito hosted UI domain"
}
