output "cloudfront_domain_name" {
  value       = aws_cloudfront_distribution._0shared_cloudfront.domain_name
  description = "Domain name generated by local CloudFront"
}

output "cloudfront_id" {
  value       = aws_cloudfront_distribution._0shared_cloudfront.id
  description = "ID of the local CloudFront distribution"
}