output "cloudfront_domain_name" {
  value       = aws_cloudfront_distribution._0shared_cloudfront.domain_name
  description = "Domain name generated by local CloudFront"
}

output "cloudfront_id" {
  value       = aws_cloudfront_distribution._0shared_cloudfront.id
  description = "ID of the local CloudFront distribution"
}

output "api_endpoint" {
  value       = aws_apigatewayv2_api.api.api_endpoint
  description = "API Gateway endpoint URL"
}

output "api_id" {
  value       = aws_apigatewayv2_api.api.id
  description = "API Gateway ID"
}

output "cognito_pool_id" {
  value       = aws_cognito_user_pool.main.id
  description = "Cognito User Pool ID"
}

output "cognito_client_id" {
  value       = aws_cognito_user_pool_client.frontend.id
  description = "Cognito User Pool Client ID (for frontend)"
}

output "cognito_domain" {
  value       = aws_cognito_user_pool_domain.main.domain
  description = "Cognito hosted UI domain"
}